### ISSUE TITLE
Notify users of species of note

### ISSUE THREAD

**Issue by bradfordcondon** [statonlab/Treesnap-mobile#256]
When the user is in a particular area, we want to be able to notify them in the mobile app that researchers would be really interested in particular trees.

This could perhaps be tied to a push notification limited to 1x a week.

**Comment by almasaeed2010** [comment]
Things to notify users about:
- [ ] Trees we are interested in (as mentioned above)
- [ ] Observations that have not been synced

Anything else?

**Comment by almasaeed2010** [comment]
Notify user of new update available

**Comment by almasaeed2010** [comment]
Currently we have "local notifications" set up on the app (see #429). This means that we can provide the user with notifications about the current state of the app without a network connection or background jobs.

To address this specific issue of notifying the user with trees of interest would require the user to grant us access of their location at all times and will need background jobs which are currently hard to create since no RN library does it right yet and we tried most of them to create the "upload in the background when wifi is present" feature. Those modules caused the app to crash silently.

**Comment by bradfordcondon** [comment]
see also #253 regarding trees we are interested in.
