### ISSUE TITLE
release and version management

### ISSUE THREAD

**Issue by bradfordcondon** [statonlab/Treesnap-mobile#372]
* We havent really been doing the "project for each release" so we can easily see what issues were closed under the project for release notes.

* incrementing the package.json file doesnt increment the xcode project file.

**Comment by almasaeed2010** [comment]
- An alternative to projects, since I keep forgetting them, is using milestones. It feels to me that they are easier to manage so maybe we could give it a try.  Also if our commit messages are clear we can run something like `git log --oneline v1.2.0..v1.2.1` to show our commits.

- I am not sure if we can automate the transfer from package.json to XCode. It feels like they are "unaware" of each other. The only way I found is a [hack method](https://medium.com/@andr3wjack/versioning-react-native-apps-407469707661) to do it with bash but they do have a good way in that post to do it in Gradle too the I think is worth it.


What are our current problems with versions in android vs ios since, if recall correctly, they are not matching?

**Comment by bradfordcondon** [comment]
i just end up setting them manually in gradle and xcode.  Setting it in  the npm config and building doesnt do anything.  As im typing this i realize thats because i need to rerun npm install after bumping verison right? oops.

sure lets try milestones.  Maybe the easy way is to ignore issues and tag the PRs instead?

**Comment by almasaeed2010** [comment]
Setting it in NPM will only show in the app's `AboutScreen`. re-installing is not necessary.

We can tag both issues and PRs as necessary using milestones since some PRs don't have issues though I am trying my best to always add issues and assign them 😅

**Comment by bradfordcondon** [comment]
The thing about issues is tagging one as 1.3, but not doing it until 1.5, means we need to remember to update the 1.3 milestones with each new app release.  Or we only tag when closed...

**Comment by bradfordcondon** [comment]
step 1: let's retroactively tag issues and/or PRs in latest releast (1.2.1) with milestones for the release.  This should just be Torreya, bug fixes, the location sorter...
