### ISSUE TITLE
"Other" trees can have multiple common names and multiple latin names

### ISSUE THREAD

**Issue by almasaeed2010** [statonlab/Treesnap-mobile#551]
The common name to latin name association is a many-to-many association. Currently we have a json list of `'latin name' : 'common name'`.  So we can only add 1 common name to each latin name.

I think the best fix is to add this to a bundled realm DB but as a temporary fix let's make each latin name take an array of possible common names:

`'latin name': ['c1', 'c2', ...]`

The search functionality (or the AutoComplete.jsx component) can then do a loop on the nested arrays and display the matches from the array.

**Comment by almasaeed2010** [comment]
The files that'll need modifying:

treeNames.js
https://github.com/statonlab/Treesnap-mobile/blob/master/app/resources/treeNames.js

And AutoComplete.js component
https://github.com/statonlab/Treesnap-mobile/blob/master/app/components/AutoComplete.js

**Comment by almasaeed2010** [comment]
The association rules are simple:

- one latin name can have multiple common names
- if a tree has multiple latin names, a new key for each latin name should be created and the common names array should be redundant for all latin names of the same tree

**Comment by almasaeed2010** [comment]
see #255 

We need to sort alphabatically (the results only).

once we find the matches we can sort the `matches` object.

**Comment by jwest60** [comment]
All keys (species names) in treeNames.jsx now have an array value of common names

Here is how a tree with multiple common names displays:
![image](https://user-images.githubusercontent.com/32902460/52084434-19260e00-2570-11e9-8773-eea25d187659.png)

Where `TEST TREE` is the species name and each of the lines above is a common name

The results are now also sorted at the end of the search function.

**Comment by jwest60** [comment]
Search is now a little smarter: searches for common names only yield the common name that matches rather than all common names for the tree and when the trees are initially listed, only the first common name is shown

Display without searching anything:
![image](https://user-images.githubusercontent.com/32902460/52151257-77222680-2640-11e9-82bc-e551bdc5612c.png)

Additionally multiple common names are now displayed comma-separated instead of on a new line:
![image](https://user-images.githubusercontent.com/32902460/52151333-b9e3fe80-2640-11e9-8ca1-4e2a6a53a047.png)

**Comment by almasaeed2010** [comment]
This is great! Thanks @jwest60 

Can you create a PR when you think this is ready?

**Comment by jwest60** [comment]
Oh oops, sorry, thought I had already created one

There's one now #564
