### ISSUE TITLE
Add circumference as an alternative to diameter 

### ISSUE THREAD

**Issue by almasaeed2010** [statonlab/Treesnap-mobile#567]
There are a few options here:

1. Add an option to compute diameter from circumference
1. Add a circumference field that auto populates diameter when filled and vice versa

**Comment by bradfordcondon** [comment]
for what its worth my thought was a checkbox for "use circumference" . that can also be set in the app settings, not unlike how we handled units (cm vs inches i think)

**Comment by almasaeed2010** [comment]
I think an option in the modal itself (option 1) is best since we won't have to do anything different to the storage.

**Comment by mestato** [comment]
We've still got a user waiting on this, let me know if we can implement. @almasaeed2010 Maybe something @jwest60 could work on?

**Comment by almasaeed2010** [comment]
Yeah @jwest60 can take it on. We just haven't gotten to it yet. I'll assign it to @jwest60

**Comment by jwest60** [comment]
added a checkbox to the modal that can compute diameter given circumference. the idea is that the user will put circumference in the textbox, check the "compute from circumference" box, then the circumference will be converted to diameter within the modal, displayed below. this also converts circumference back into diameter when unchecked

![image](https://user-images.githubusercontent.com/32902460/56685591-4a5e3800-66a0-11e9-8b65-5b7ed4e8fd3f.png)

![image](https://user-images.githubusercontent.com/32902460/56685662-7974a980-66a0-11e9-9fd9-1b9ac4269856.png)

however, this doesn't work if the user first checks the box to compute from circumference, then inserts their circumference. once the modal is closed, the form will assume that the circumference provided is actually the diameter

the other option would be to compute the circumference only after the modal is closed. in this case, the user wouldn't actually see any changes to their input until they return to the form page, i.e. they see this

![image](https://user-images.githubusercontent.com/32902460/56686095-50084d80-66a1-11e9-8218-93799f9a8f3f.png)

then they would see this on the form after they close the modal

![image](https://user-images.githubusercontent.com/32902460/56686166-7201d000-66a1-11e9-8435-f83dae022364.png)

this seems a little more intuitive to me instead of doing it within the modal, but i still think its possible that a user might think the form is misinterpreting the value or it might not be totally clear what that checkbox does until they return to the form

the changes are available [on this branch](https://github.com/statonlab/Treesnap-mobile/tree/circumference) if anyone wants to play around with them

**Comment by almasaeed2010** [comment]
@jwest60 did you try using the onBlur event to do the computation?

**Comment by jwest60** [comment]
added an onblur effect to the tree diameter numerical input that will change the value in the textbox whenever the keyboard is closed if the use circumference box is checked

**Comment by almasaeed2010** [comment]
One last thing for this. Let's round to 2 decimal points in `onBlur` only of the compute from circumference is added. New branch please.

**Comment by almasaeed2010** [comment]
thanks @jwest60
